### ISSUE TITLE
support tutorial accounts

### ISSUE THREAD

**Issue by ahelsing** [ahelsing/tickettest2#200]
Infra and the experiment support team would like support for 'tutorial accounts' and maybe 'tutorial projects', for ease in running tutorials.

 _Imported from trac ticket [#200](http://trac.gpolab.bbn.com/proto-ch/ticket/200),  created by ahelsing on 08-21-2012 at 15:23, last modified: 02-12-2013 at 16:03_

**Comment by ahelsing** [comment]
Tutorial projects probably have an explicit, short duration.
Maybe these are a type, such that certain users can be limited to only such projects.

Tutorial accounts from our IdP would then send an account expiration and 'tutorial=True' or some such over Shibboleth. Then the portal/CH would give you certs/credential that obey that expiration, limit your privileges based on that expiration, and only put you in tutorial projects based on that flag.

Scripts to auto do tutorial set up are good
 - create account
 - add account to project
 - create SSH keys
 - create cert/key
 - download the cert/key/SSH private key/omni config/?


_Trac comment by ahelsing on 08-21-2012 at 15:25_

**Comment by tcmitchell** [comment]
We have a mechanism for tutorial accounts in place. Projects have expiration times. We'll prefer real named accounts at home IdP or GENI Idp, but can create temporary accounts on the GENI IdP if necessary (for walk-ins). That's sufficient for this ticket.

_Trac comment by tmitchel (github user: tcmitchell) on 02-12-2013 at 16:03_
