### ISSUE TITLE
Pretty names on slice users always show current user

### ISSUE THREAD

**Issue by tcmitchell** [ahelsing/tickettest2#206]
The 'pretty names' in the slice members table don't work, they all get the name of the current user. This is probably related to the recent changes to `geni_loadUser()`.

 _Imported from trac ticket [#206](http://trac.gpolab.bbn.com/proto-ch/ticket/206),  created by tmitchel on 09-07-2012 at 08:55, last modified: 09-10-2012 at 14:05_

**Comment by tcmitchell** [comment]
I can't reproduce this problem. Marshall is going to try to reproduce.

_Trac comment by tmitchel (github user: tcmitchell) on 09-10-2012 at 13:49_

**Comment by MarshallBrinn** [comment]
All fixed - tom and I found an obsolete call to geni_loadUser($member_id) instead of $user->fetchMember($member_id);

_Trac comment by mbrinn (github user: MarshallBrinn) on 09-10-2012 at 14:05_
