### ISSUE TITLE
Change "manifest" to "details" on button label

### ISSUE THREAD

**Issue by tcmitchell** [ahelsing/tickettest2#332]
The label "manifest" isn't useful for those unfamiliar with the inner workings of the AM API. Try labeling the button "details", and include a tool tip indicating that it shows login and other resource specific information.

 _Imported from trac ticket [#332](http://trac.gpolab.bbn.com/proto-ch/ticket/332),  created by tmitchel on 11-09-2012 at 15:49, last modified: 11-09-2012 at 22:54_

**Comment by seledwards** [comment]
The `title` attribute of a `<button>` appears as a tooltip.  

 1) In `slice.php` changed button name to "Details" and added title text "Login info, etc" in 2 places.
 2) Same in `tool-slices.php`.
 3) In `tool-breadcrumbs.php`, changed breadcrumb from "Manifest for Slice <slicename>" to "Resources on Slice <slicename>".

I greped the `proto-ch/portal/www/portal` directory for other instances of the string "anifest" and don't see any other changes that need to be made.

Closing.  Feel free to reopen as necessary.

_Trac comment by sedwards (github user: seledwards) on 11-09-2012 at 22:54_
